name: CI Checks

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'


      - name: Install Server dependencies
        working-directory: ./server
        run: npm install

      - name: Run Server tests
        working-directory: ./server
        run: npm test --if-present

      # --- ПЕРЕВІРКА ТА ЗБІРКА ФРОНТЕНДУ ---
      - name: Install Frontend dependencies
        working-directory: ./frontend
        run: npm install

      - name: Lint & Test Frontend
        working-directory: ./frontend
        run: |
          npm run lint --if-present
          npm run build